### ISSUE TITLE
mobymax language

### ISSUE THREAD

**Issue by xczuey** [futzumi/Moby-Max-Hack#10]
does it only work for mobymax math because when i press the skip lesson button on mobymax language it does nothing

**Comment by xczuey** [comment]
read that multiple choice hack was removed

**Comment by futzumi** [comment]
@xczuey I'll look into it for version 3.1

**Comment by futzumi** [comment]
@xczuey I fixed this, if you notice it in any other sections, let me know

**Comment by xczuey** [comment]
Hack works fine, will check if it fails to skip in other sections.

**Comment by futzumi** [comment]
alright thanks. Make sure to check at the recent version of the hack. You can add an hour to your weekly time every day
