### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by germs987** [futzumi/Moby-Max-Hack#11]
I think they patched the hack, please help

**Comment by germs987** [comment]
nvm
but can you add show answer because i dont want to skip the whole thing

**Comment by futzumi** [comment]
The show answer hack got patched, thats why i replaced it with skip lesson. I can add a skip answer hack if you want

**Comment by germs987** [comment]
yes plese because the it wont work on the test

**Comment by futzumi** [comment]
Me and phillip are still working on a test version of everything
