### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ghost** [futzumi/Moby-Max-Hack#3]
If you could add a completely afk mode that answers, even fill in the blank ones that would make this perfect
also maybe a game time minutes hack?

**Comment by VirescentOverlord** [comment]
I can only try but im not sure if i can garountee anytime soon

**Comment by Dom0336** [comment]
it dose not work on bench marks

**Comment by elliot235** [comment]
yo virescent, your a beast bro. thank you so much man! right now feb 26 2023 the hacks are not working it says "Made By Virescent Overlord, The solution is: undefined" could you help me with this?

**Comment by futzumi** [comment]
First of all ghost, if you go to [phillipbruh's](https://github.com/phillipbruh/snowplus/blob/main/mobymaxbotconceptsource) hack, me and him worked together to make an afk version. I also attempted any times to find a way to get free minutes but that would include me rewriting code in their server which is highly illegal.

**Comment by futzumi** [comment]
@elliot235, Moby max has patched most of this hack. Now, with the newest and recent updates, it only works on some learning paths

**Comment by futzumi** [comment]
> it dose not work on bench marks
> 

I cant make a benchmark version because my school doesn't even use moby max. the account I snatched is also inactive so I dont think there will be a benchmark hack anytime soon
